### ISSUE TITLE
Nakalim Missing core ESG features

### ISSUE THREAD

**Issue by Provolonage** [wakystuf/ESG-Mod#1000]
Edit for Documentation:
1. Nakalim start with Friendly Locals Anomaly
2. Nakalim Unstable Isotope Machining doesn't scale per Pop
3. Nakalim Scout and Colonizer both start with their empty slots replaced with engines
4. Give Nakalim unique effect for Cram Exam (re-lore it), +5 Science (+10) per Temple on System, -2 Approval per Pop on Planets with Temples
5. Nakalim Chapter 4 part 1 system conversion requirement lowered from some awful number scaling with galaxy size to +3
6. Nakalim should get weaker variant of arcological admin

Nakalim home planet (Sobra) does not come with an anomaly unlike every other home planet, basically any would work for them, but hollow planet would be nice since Sobra only has 5 pop slots, just feels awful to start with green fertility and not be able to use it.
Nakalim Unique Defense building (On Unstable Isotope Machining) don't scale with pop like current ESG one's do making them significantly worse late game. 
Nakalim colonizer (Petitioner) starts with an empty support slot, please put an engine in there.
Nakalim scout comes with an empty support slot, but this is most likely due to us moving the bonus scout slots to steppes tech so idk if this can be fixed.

**Comment by Arpharnator** [comment]
second point got fixe a few days ago
first point i agree

**Comment by ThanosDeGraf** [comment]
first point husk does not have guaranteed anomaly either (or any of the other planets for that matter)
Agree on all other points.

**Comment by wakystuf** [comment]
Yeah, Tchinomy doesn't have an anomaly either, nor does Nexus.

**Comment by captaincobbs** [comment]
Nakalim don't get an anomaly, #2 is finished already, #3 and #4 I can do

**Comment by Provolonage** [comment]
why they literally start with access to green fertility bill and cant use it

**Comment by Provolonage** [comment]
also sobra is kinda shit it has negative pop slots

**Comment by captaincobbs** [comment]
Fine, I think giving them friendly locals would be best then

**Comment by Provolonage** [comment]
pog

**Comment by wakystuf** [comment]
Yeah this all seems fine to me; feel free to code it whenever you want and I'll review/merge
