### ISSUE TITLE
Morale bonus is broken

### ISSUE THREAD

**Issue by Arpharnator** [wakystuf/ESG-Mod#1009]
Might be due to the earlier tempering of waky with evasion to make sure it worked properly but either way 60% is too much so now it's halved

**Comment by captaincobbs** [comment]
Waky!! Stop tampering

**Comment by wakystuf** [comment]
It's not really 60%; it's already only 30% because the game effectively divides it by 2 through accuracy correction

**Comment by Arpharnator** [comment]
dude you haven't watched the battles cuz im telling you that my shit is missing 60% of my shots it's a bit insane

**Comment by Arpharnator** [comment]
also i need to remind you that you made it so that evasion is multplied by 2 on a ship level iirc and that morale is distributed to each ship so they end up with the 60%

**Comment by wakystuf** [comment]
That's not quite right, though I know what you're talking about. I multiplied it by 2 when it's passed to ClassShip specifically from ClassEngine and ClassDefenseModule, but NOT in other cases. For the other random sources of evasion I doubled them but then forced the GUI to report the lower numbers. Here's a good example that shows what's going on:
https://github.com/wakystuf/ESG-Mod/pull/782/commits/1926ed7174967a1438d1e31b2b702316dd26b047

**Comment by Arpharnator** [comment]
i dunno and idc i just saw my ship miss 60% of shots without other modifiers and it's not fine

**Comment by Arpharnator** [comment]
unless you tell me that i can just team spirit far all that exists and it's fine getting > 100% evasion

**Comment by NoProblemWithThisAcc** [comment]
Arphar, is this reproducible? Can we get a screenshot? That sounds nuts unless there's evasion-piercing stuff I'm unaware of

**Comment by wakystuf** [comment]
What was the context for that battle? Was the other side using Team Spirit and did they actually have a full 2 more flotillas?

I do like that morale is a good incentive to avoid lane stacking

**Comment by Arpharnator** [comment]
it was 30 scouts vs a carrier using swarms at long range and i missed a fuckton

**Comment by Arpharnator** [comment]
2 flotillas and battlecards that did nothing in that context

**Comment by wakystuf** [comment]
Oh, well swarms might be part of the issue then, no? I'm not sure how they work with overkill, but if the targeting is set at the beginning of a salvo then it could cause a large chunk of the issue.

I'm assuming that missed shots are supposed to be 35% if you were 1 flotilla vs 3 (15 x 2 morale and then 5% from swarms at long)?

**Comment by Arpharnator** [comment]
no i watched the battles and they just miss for 0 reason will the ennemy isn't dead

**Comment by Arpharnator** [comment]
*apart from morale
