### ISSUE TITLE
bombers deal far too much damage

### ISSUE THREAD

**Issue by Arpharnator** [wakystuf/ESG-Mod#1011]
title basically.
I was testing the unfallen plating with this ship :
![image](https://user-images.githubusercontent.com/49691625/147854185-2539b75e-6375-4182-a120-dddcb4af70c9.png)
vs this one
![image](https://user-images.githubusercontent.com/49691625/147854191-2834255c-d61c-40d7-8edd-64bf06f66c0a.png)
and i swear i took more than 65% of my health a few times for some reason while sometimes they would deal just barely 20%, which is still way too high considering i have 93% plating.

**Comment by wakystuf** [comment]
Can you show an example of damage dealt vs missiles of the same tier?

**Comment by Arpharnator** [comment]
a single bomber attack would deal 2000 damage at the lowest with my 93% plating while the missile deals like 200?

**Comment by wakystuf** [comment]
Hmm...I suspect part of the issue there is the crit, right? Doesn't that bomber module come with a pretty high crit %, maybe 25%?

**Comment by Arpharnator** [comment]
bomber is only supposed to give like double damage which is fuckall if i have 93% plating.

**Comment by wakystuf** [comment]
You're saying that bomber crits don't bypass defenses?

**Comment by Arpharnator** [comment]
no they don't it says in the tooltip and the post battle numbers looking at crit make sense. so i don't know what's acting aloof apart from the fact they deal a ton of damage, maybe need to check their penetrations but they shouldn't have jumps of damage neither should they deal that much damage against a fitted carrier

**Comment by wakystuf** [comment]
OK, well it feels like we should probably do a test of 2 situations:
1) What you just did, and paste the screenshot showing the damage dealt, etc etc
2) Same thing except using T5 missiles

Then we can compare the damages and try to bring them more in-line (goal wouldn't be to bring them all the way down since bombers should be better vs large hulls, but should be reasonably close).

I suspect that part of the issue is that bombers offensively improve with MM ^2, while most other stuff is only linear. That's because both squadron count and DPS per squadrons grows with MM, and then the 2 are effectively multiplied, I believe.

**Comment by Arpharnator** [comment]
possible but it's true that it's a bit cringe seeing 700+ dps squadrons bc it's on a carrier

**Comment by Eighth-of-Third** [comment]
> I suspect that part of the issue is that bombers offensively improve with MM ^2, while most other stuff is only linear. That's because both squadron count and DPS per squadrons grows with MM, and then the 2 are effectively multiplied, I believe.

Oh fuck, really? I thought the squadron count just doubled and that doubled the dps. If that's true, that needs to be changed.

**Comment by wakystuf** [comment]
@Eighth-of-Third I believe so. Both squadron count and DPS should display in the GUI, so it's easier to see than some of the stuff that happens by black magic in the back-end. Take a spin through and see if you come to the same conclusion. I can also double check in the code that DPS is independent of squadron count.

**Comment by Arpharnator** [comment]
actually i've tested a litle bit more yesterday, and it seems like the issue comes from the part where the damage multiplier of bombers is dealt above the resistances of the attacked ship.
This comes from experimenting with fighters and bombers, where i could see that fighters wouldn't even deal a single point of damage to a carrier, while bombers wouldn't even deal a single point of damage to smalls with enough % defences. (plating) (this is at least true for the kinetic variants, energy reduction doesn't exist so energy squadrons will always deal damage)
As such I believe that the bomber damage being inbalanced comes from the fact that their bonus damage is dealt after the primary (non % size modified damage) and as such is deal in full.
ex : 130% damage bonus to large. 90% plating ship. 200 dps squadron. 1000 damage per shot.
squadron shoots on large -> 1000 *0.1 = 100 
bonus damage applied -> 300
total damage : 400 and not 130

**Comment by Arpharnator** [comment]
>I suspect that part of the issue is that bombers offensively improve with MM ^2, while most other stuff is only linear. That's >because both squadron count and DPS per squadrons grows with MM, and then the 2 are effectively multiplied, I believe.

also lies i checked

**Comment by wakystuf** [comment]
Interesting. If that is really how the size-based bonus damage works, then we should try to fix it in BattleEffectDefinitions or something.

Regarding the MM^2 what did you check? Within SimulationDescriptors[ModuleSquadron].xml, you can clearly see both of these 2 lines:
`  <Modifier TargetProperty="Damage" Operation="Multiplication" Value="$(Multiplier)" Path="ClassModuleSquadron" TooltipHidden="true"/>
  <BinaryModifier TargetProperty="BomberUnitsCount" Operation="Multiplication" Left="$(Multiplier)" BinaryOperation="Division" Right="2" Path="ClassModuleSquadron,SquadronTypeSquadronBomber" TooltipHidden="true"/>

`

**Comment by Arpharnator** [comment]
or myabe your right idk if the dps diplsayed on the GUI is for a single bomber or for both

**Comment by wakystuf** [comment]
The code for the DPS is shown later in that same file; I think it's just Damage divided by [the variable for how long their sorties last].

The division by 2 is irrelevant to the fact that the scaling is quadratic instead of linear. X * X/2 is the same thing as 50% * X^2.

**Comment by Arpharnator** [comment]
the things you sent earlier don't seem to be correct tho, bc having 2 mm would mean that you have 2 bombers, but in reality you get 1.
Same for mm 4, you should get 8 but you get 2

**Comment by wakystuf** [comment]
What? How are you getting those numbers? 

With 2 MM you should get 1 bomber (2/2 =1) and with 4 MM you should get 2 bombers (4/2=2). So that sounds correct, right?

**Comment by Arpharnator** [comment]
50% * X^2
X = 2
0.5 * 4 = 2
X = 4
0.5 * 16 = 8

**Comment by wakystuf** [comment]
No no no.

The X^2 is referring to overall effective damage, not the count of # of bombers.

Let's say the module says it does 100 Damage.
* Coordinator is 2 x 100 = 200 Damage, and 2 / 2 = 1 Bomber, so 200 total Damage
* Carrier is 4 x 100 = 400 Damage and 4 /2 = 2 bombers, so 800 total Damage

MM from Coordinator to Carrier is effectively 2x (since it's going from 2 to 4). However, Damage is 4x, which is 2^2.

Make sense?

**Comment by Arpharnator** [comment]
ah yes i forgor that you were talking about dmg not bombers

i'll launch the game real quick to verify
if coord to carrier is 4 times

**Comment by Arpharnator** [comment]
coord
![image](https://user-images.githubusercontent.com/49691625/148570257-3e304cbb-efb2-43c2-90c6-007aafedab0c.png)
carrier (don't take the 10% into account)
![image](https://user-images.githubusercontent.com/49691625/148570296-87d5ad0b-34a9-49c3-8b95-64336db93a26.png)
so it's lies unless the game only show the damage of a single bomber

**Comment by wakystuf** [comment]
Right. I think it is the DPS of a single bomber, but you can check the code too. As I said earlier, I think DPS = Damage / [how often bombers attack]. I don't think it is multiplied by the count of bombers unless that's happening someplace else.

**Comment by Arpharnator** [comment]
@wakystuf i tested and it turns out you're a fucking liar
![image](https://user-images.githubusercontent.com/49691625/148571611-b2234c4f-2ce3-497f-a508-2397f2bc9dad.png)
bad waky bad

**Comment by Arpharnator** [comment]
the damage is high bc of size mult and carrier 10% bonus

**Comment by wakystuf** [comment]
What am I supposed to conclude from that screenshot? The 6534 damage?

**Comment by Arpharnator** [comment]
that it's not dealing 13000 damage and as such that the game is not liying and that the numbers we are shown are accurate

**Comment by Arpharnator** [comment]
since damage is (4.5k * 1.10) * 1.25 = 4995 * 1.25 = 6.5k

**Comment by wakystuf** [comment]
And where does the 4.5k come from vs the 660 on the module?

**Comment by Arpharnator** [comment]
it's the base damage of the adamantium squadron

**Comment by Arpharnator** [comment]
lie you know dps * how often bombers attack

**Comment by wakystuf** [comment]
I'm seeing this in the code:
`    <Modifier TargetProperty="Damage" Operation="Addition" Value="660" Path="ClassModuleSquadron"/>`

**Comment by Arpharnator** [comment]
![image](https://user-images.githubusercontent.com/49691625/148576647-9e5bca41-4eca-44ac-910d-9ceb9a315683.png)

**Comment by Arpharnator** [comment]
<Modifier TargetProperty="Damage" Operation="Addition" Value="990" Path="ClassModuleSquadron"/>

**Comment by wakystuf** [comment]
Oh, looks like I was pulling an older branch, yeah. But doesn't that prove that Damage is scaling with MM, just like I said? Since that's separate from the # of bombers.

**Comment by Arpharnator** [comment]
that just proves it's scaling normally, damage is indeed 4 times and not 8 times, so that makes liaar

**Comment by wakystuf** [comment]
But that's the damage per bomber, right?

**Comment by Arpharnator** [comment]
no

**Comment by Arpharnator** [comment]
the screenof the damage being dealt to the carrier proves it

**Comment by wakystuf** [comment]
Does it? I only see 1 bomber there.

I think you'd need to test again with a Coordinator sending the bomber to see if it's 50% or 25% as much as the 6500

**Comment by Arpharnator** [comment]
can't you se the separation in the middle of the bomber reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by wakystuf** [comment]
Isn't that separation showing this? (the Carrier has the same thing)
Current Health
_________
Max Health

**Comment by Arpharnator** [comment]
![image](https://user-images.githubusercontent.com/49691625/148577795-ea2cae6b-374c-4275-9eff-906d102faa0c.png)
get gapped kidd eeyyyyy easy

**Comment by Arpharnator** [comment]
no i mean there is vertical line of nothing separating the visual circle health of the bomber in 2

**Comment by wakystuf** [comment]
Eh? I still don't see the second bomber in the pic from the carrier; where is it on the screen?

**Comment by Arpharnator** [comment]
get  gapped

**Comment by captaincobbs** [comment]
Closed due to inactivity.
