### ISSUE TITLE
Rework Scavenger Capstone

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#1012]
New effect TBD

**Comment by wakystuf** [comment]
Proposal: +2 lux of each type used by the empire for SD, if we can figure out how to mod that

**Comment by NoProblemWithThisAcc** [comment]
Detecting which lux is used for SD would be SO USEFUL to help ease the luxury roulette RNG that is the most frustrating bottleneck in the game.

**Comment by wakystuf** [comment]
![image](https://user-images.githubusercontent.com/79942510/148692621-173b955b-815b-4c06-8981-bb4701bd5852.png)
