### ISSUE TITLE
Balance start

### ISSUE THREAD

**Issue by Arpharnator** [wakystuf/ESG-Mod#1013]
Horatio : done (todo : fix the system's curios)
everything else : not done

In regards to custom factions, the current prerequesites to trigger the balance start is to have the same initial populations as the standard empire.
The reason for that is that if the system is made anew without removing the population in the system, the growthstock is still present and as such when starting the game you will find yourself with several hundred worth of food stockpiled and ready to use, which is not what we want.
Since the only way to deal witgh this problem is to remove the starting populations before remaking the system, it is necessary to be able to target the populations properly, thus leading to customs without the same starting pops to be unable to use it.

**Comment by Arpharnator** [comment]
Actually since technically speaking all customs start with some other sort of pop it might be impossible for customs to use the balanced start (which is fine by me since customs aren't balanced anyways).

**Comment by captaincobbs** [comment]
Not having customs with balanced starts isn't a big deal in my opinion, though we should clarify that in the tooltip

**Comment by Arpharnator** [comment]
update on this as its finished

**Comment by wakystuf** [comment]
I haven't tested it or anything, but I did briefly flip through the code and this looks great; nice job!

We should probably discuss what planets you allocated to which factions, etc; can you maybe create a table or some kind of summary when you get a chance?

**Comment by wakystuf** [comment]
@Arpharnator 
1) Once again, this is awesome.
2) Before we merge, can you make something like what I made for Vodyani so that we can all look at the systems and agree on what is a balanced start? (note that the Vodyani one has 16 options, vs this will have only 1 for each faction, so it'll be less work)

![image](https://user-images.githubusercontent.com/79942510/148656240-9fd7375a-6dd9-46a3-a57e-871c374d3497.png)

**Comment by Arpharnator** [comment]
absolutely not, not gonna make 16 systems, at least yet

**Comment by wakystuf** [comment]
Below is the prior proposal, I believe. I'll post my suggested version in a moment

**Comment by wakystuf** [comment]
Here is what I'd suggest:
* All factions should get a T0, a T2 and a T3 planet
* I'm fine starting them all with titanium and hyperium and no other resources (which is I believe how it's set up now?)
* Each faction should get a mixed anomaly on their T0 planet and a positive anomaly on their T2 planet
* 2 total loot curiosities
* I'd suggest the following distribution of planets:
![image](https://user-images.githubusercontent.com/79942510/148663492-6ccd17c4-6874-456b-adb6-40d230c5b581.png)

**Comment by Zingybird** [comment]
Can cravers not have a ice make a hot planet's but anything is better than Arctic

**Comment by wakystuf** [comment]
They can maybe have a Swamp, but I think giving them a Hot is going to make them more rush-y, which we probably want to avoid

**Comment by Zingybird** [comment]
A swamp is even worse and the whole point in the faction is too rush why not give them ash than or desert

**Comment by captaincobbs** [comment]
you're not supposed to get what you want

**Comment by Arpharnator** [comment]
>All factions should get a T0, a T2 and a T3 planet
it should also depend on the starting plnanet because it's known that some starting planets are quite bad for the faction, for example ratio unable to use xeno or ppp, sophons with a boreal that's quite a weak planet, rb with snow that doesn't give them bonuses and maybe others im forgetting

**Comment by wakystuf** [comment]
Sure, but that's why RB get a Desert, which is pretty delicious (I know they'd prefer a Lava, but I don't think we want to give them exactly what they want).

Are there any that you would change on that basis?

**Comment by Arpharnator** [comment]
well i'd rather give factions what they need/want to some extent. RB getting lava is a staple for good colonizer making which is an important part of rb gameplay. So that's why in general I'd argue for beneficial starting conditions for the factions in general

**Comment by Arpharnator** [comment]
like desert isn't gonna do anything for rb at the time they need it on their homesys, which is at the start of the game. Later on it's nice to have a desert but it definitely feels more like a drop of water in the ocean than something useful at this point.

**Comment by wakystuf** [comment]
What? It's still a significant upgrade from the Snow that they start out on; it's a pretty yummy thing to have

I don't want this to be an overall buff to the factions getting the starts rebalanced; it's more about making the starts reasonable and average, not weak and not strong. So no forest/monsoon/tundra for RB, but also no lava

**Comment by captaincobbs** [comment]
Has this been merged yet?

**Comment by wakystuf** [comment]
No. Arphar needs to incorporate some changes first. If he doesn't do it by the time the other galaxy gen stuff is finished, then I'll just update the planets myself and merge it at that point (since it will go well with the galaxy gen changes)

**Comment by captaincobbs** [comment]
Alright, someone might want to update this to the current 1.5.1 before it gets hard

**Comment by wakystuf** [comment]
Yeah, it's a good idea. Once I merge the galaxy gen stuff (hopefully in the next couple of days), it will hit some of the same files, so likely makes sense to do the reverse-merge after that

**Comment by Arpharnator** [comment]
I thought we needed to talk with the members of the senate about this, but they havennt responded to this at all.
I guess i'll just do it using the stuff you provided.

**Comment by Tat011** [comment]
can we have a table comparing what we have now to the new changes? i don't really remember the spawns by memory (exept that ue spawns with 2 swamps for some reason)

**Comment by Arpharnator** [comment]
rn there is nothing

**Comment by captaincobbs** [comment]
I remember them not giving helpful feedback, just implement it as waky suggested and if they have problems with it, it's on them for not giving feedback on it.

**Comment by captaincobbs** [comment]
Could someone make an updated chart for all factions? (Including Vaulters)
