### ISSUE TITLE
Make energy fighters deal 100% damage to small

### ISSUE THREAD

**Issue by Arpharnator** [wakystuf/ESG-Mod#1048]
since fighters are useless and kinetic ones were made to be 100% on small, then i propose we do the same for energy ones

**Comment by wakystuf** [comment]
Seems logical to me. I assume there's no reason we didn't already do this; it was simply forgotten?

**Comment by Arpharnator** [comment]
i think at first it was because we didn't want to have fighers have high % vs smalls bc shield don't offer any resistances so that was why. However if we start thinking about the already smaller damage alongside the fact that we have a good guess as to how squadrons work i propose we buff it.

**Comment by Arpharnator** [comment]
can i go on with this?

**Comment by wakystuf** [comment]
Yes, go ahead
