### ISSUE TITLE
[AI] Lower amount of behemoths slots gotten from difficulty for AI

### ISSUE THREAD

**Issue by Arpharnator** [wakystuf/ESG-Mod#1049]
Seems to have an adverse effect on performance, with AI building very costly ships but then displaying behavior where they make them sit in their hangar or orbit a system meaninglessly

**Comment by Arpharnator** [comment]
![image](https://user-images.githubusercontent.com/49691625/149630359-4eaf45f0-54f5-40cb-8bd3-af98c40063b8.png)
proof of AI being a derp

**Comment by Mermixer** [comment]
omw to buy out my pop

**Comment by Arpharnator** [comment]
honestly I'm considering not allowing AI to research behemoth tech, it's a massive roablock for them and they can't even use them correctly

**Comment by NoProblemWithThisAcc** [comment]
Do they obey max behemoth limits? We could just remove their bonus behemoths and if necessary force their behemoth limit to 1.

If their single military behemoth actually acted as a tank (post-buffs) and comes out cheaply (they are initially very cheap and THEN become ridiculously expensive), it would be fine and make players think the AIs are acting like a player.

**Comment by captaincobbs** [comment]
Merge into issue #996

**Comment by Arpharnator** [comment]
Closed since merged into issue #996
