### ISSUE TITLE
Include Sophons Pacifist Quest Rewards in the Dust -> Temperate changes

### ISSUE THREAD

**Issue by Kil10naire** [wakystuf/ESG-Mod#1052]
As the title suggests, the final quest reward for the Sophon Pacifist line was exempt from the changes.

**Comment by captaincobbs** [comment]
Should we also make it add flat dust to the planet? Temperates don't produce much dust

**Comment by Kil10naire** [comment]
I want to say no, since you can terraform everything to some of the good Fertile Planets like Ocean to get all the benefits of that as well as the extra dust. Also assuming you are going through with the changes that you said earlier, +32 dust per pop seems alright to me.
"Toxic -> 16 Dust, 2 Food, 2 ind, 2 sci
Steppes -> 12 dust, 4 food, 1 ind, 3 sci
Savannah -> 12 dust, 4 food, 3 ind, 1 sci
Monsoon -> 8 dust, 6 food, 2 ind, 2 sci "
