### ISSUE TITLE
Fix Deployment Capacity

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#1059]
No real way to increase it during lategame, try to figure out some way to make it scale with garrison capacity / garrison manpower without breaking things like last time.

**Comment by Mermixer** [comment]
can you please elaborate whats the issue is here, you mean like the 26k isnt enough or am i understanding this wrong

**Comment by NoProblemWithThisAcc** [comment]
Since you said "please," I think cobbs wants to not make the Deployment Capacity just some (maximally) large number because it confuses noobies. Instead it should seem like the amount of manpower capacity is merely equal to the amount that about to be deployed so it make sense that all your manpower is deployed

**Comment by Arpharnator** [comment]
@Mermixer 
sometimes you get like 100k+ although rare
also confusing for the unskilled

**Comment by Mermixer** [comment]
i mean
if either side is trying to ground invade a system with 100k mp
then theres definetly related to the unskilled

**Comment by Arpharnator** [comment]
or you have 400k mp sitting in the corner so not always but if you reach that point it might be related

**Comment by captaincobbs** [comment]
You cannot escape responsibility waky

**Comment by wakystuf** [comment]
What? I don't even know how to do this one. I'll just change it to 999999 and be done

**Comment by captaincobbs** [comment]
Make all the defense strategies make deployment capacity be equal to either garrison capacity or current garrison

**Comment by captaincobbs** [comment]
Either that, or make all the things that increase garrison capacity also equal deployment capacity equally.

**Comment by wakystuf** [comment]
Ugh, fine. I did it. Don't say I never did anything nice for you, @captaincobbs
