### ISSUE TITLE
All 3rd Collection Bonus tooltips are missing

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#1060]
Where did they go, who took them

![image](https://user-images.githubusercontent.com/16710532/151745253-dd79f768-138f-45b4-890e-e554ee6a4b05.png)

**Comment by wakystuf** [comment]
I have a strong suspicion that this was caused somehow by the tooltip rework; I'm going to unassign myself for now unless @captaincobbs disagrees

**Comment by captaincobbs** [comment]
Didn't touch those in the tooltip effect rework

**Comment by captaincobbs** [comment]
I'm not fixing this, someone else will.

**Comment by wakystuf** [comment]
Can someone replicate this issue? It seems fine to me (and I looked at other factions/pops as well--they also seemed fine)
![image](https://user-images.githubusercontent.com/79942510/154194575-b4b46edb-1a2d-4d4c-90e4-c53ff384de75.png)

**Comment by wakystuf** [comment]
![image](https://user-images.githubusercontent.com/79942510/154195917-a509da77-a1e2-4cff-bbbf-04f94d497381.png)

**Comment by captaincobbs** [comment]
It's fixed?

**Comment by captaincobbs** [comment]
If this error is discovered again in the future, we'll reopen this, but as far as Waky and I can tell, the error has fixed itself.
