### ISSUE TITLE
Democracy Buff

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#1063]
A small buff to make democracy more worthwhile, to wrap up all the government changes.

Make Democracy's power laws gain an additional effect for each secondary party (so, 2 of the effects listed below will be added to the power law based off of the other parties in power).

|Party|Effect|
|---|---|
Industrialist|7.5% Industry Spent -> Dust
Scientist|+1 Movement on Ships
Pacifist|+10 Approval while not at War
Ecologist|+25% Initial Planet FIDS
Religious|-10% Hero Unlock Threshold
Militarist|+10 Approval while at War

**Comment by stygmaskyzoo** [comment]
are the coalition laws going to happen?

**Comment by captaincobbs** [comment]
Nope

**Comment by Arpharnator** [comment]
Is this getting cancelled then?

**Comment by captaincobbs** [comment]
No

**Comment by captaincobbs** [comment]
Update to this + many other content additions I had planned. I no longer have time to implement them, so I will be unassigning myself from everything.

**Comment by captaincobbs** [comment]
Please do not close these issues in case someone is willing to pick them up.

**Comment by wakystuf** [comment]
I think with the change to propaganda this buff may no longer be needed. I'll close this issue if nobody yells at me in the next day or so
