### ISSUE TITLE
Make Faction Variants of Buildings Incompatible with Eachother

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#1067]
Example:
Make Glacial-Sanitization Laboratories incompatible with Public-Private Partnerships and vice versa.
Go through all buildings and make sure they are incompatible.

**Comment by wakystuf** [comment]
I believe the RB specific versions already have this fixed, so this is likely a false alarm. Is there a specific building that seems to be duplicated?

**Comment by wakystuf** [comment]
I can find no examples of this; closing due to false alarm

**Comment by captaincobbs** [comment]
Reopening because I know there are still problems

**Comment by captaincobbs** [comment]
Went through and found all of them
Aurigan History Center and Culture Center
Budakai Bunkers and Impervious Bunkers
Kamdir Martial School and Planetary Guard
Research Cities and Optics Research Labs
