### ISSUE TITLE
Make a spectator faction

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#138]
Note: ShipTypeIndestructible

**Comment by wakystuf** [comment]
This was listed in the v1.3 portion, but it seems to be open. Should it be moved out of 1.3's wiki?

**Comment by captaincobbs** [comment]
It was delayed several times because we kept finding more and more problems. It's currently planned for 1.3.2, so yes.

**Comment by captaincobbs** [comment]
Keeping this here as a reminder, this will be moved to its own repository though.

**Comment by captaincobbs** [comment]
Not happening
