### ISSUE TITLE
Automatically unlock Battle Tactics for the AI as Era Unlocks

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#278]
The AI doesn't have the ability to research battle tactics cards. I propose that the AI automatically unlocks specific cards depending on difficulty when it reaches an era in order to increase AI intelligence.

**Comment by NoProblemWithThisAcc** [comment]
If the AI can't gain/equip them as tech unlocks but can as era/deed rewards, agreed. They should be allowed to have on hand the 6 best all-purpose cards, unless we find niche cards the AI is really good at.

But why can't they use the off techs?

**Comment by captaincobbs** [comment]
Depend on #79 being finished.

**Comment by captaincobbs** [comment]
No one wants to do this

**Comment by captaincobbs** [comment]
Reopening as a possibility since it crossed my mind a while ago, this is still an issue.
