### ISSUE TITLE
Balance Module tier costs, remove ship base cost increase per Military Tech Stage

### ISSUE THREAD

**Issue by Doruk-Coskun** [wakystuf/ESG-Mod#385]

**Comment by captaincobbs** [comment]
Delayed due to time constraints

**Comment by Arpharnator** [comment]
guess ships don't scale with military era, what is left is doing module cost rebalance

**Comment by wakystuf** [comment]
Oh, I thought they did at the moment? I know we've changed that back and forth so I could be wrong

**Comment by Arpharnator** [comment]
no they don't, as such now whats left is the module cost rebalance

**Comment by wakystuf** [comment]
Interesting, OK.

**Comment by captaincobbs** [comment]
Not finished, only common modules were done, and it doesn't yet affect ship trade value like intended

**Comment by wakystuf** [comment]
OK sounds good. I'm going to unassign myself so that it doesn't show up when I filter anymore

**Comment by wakystuf** [comment]
Update: now scales with MM, as well as the the Large Weapon tag
Also added the couple of modules that Provo said he couldn't find
