### ISSUE TITLE
Hero Skill Rework

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#532]

**Comment by Arpharnator** [comment]
https://docs.google.com/spreadsheets/d/1pMpsg8Ag9zr8K4fjOVrQwkMHSJkt79xLORBoa-X9yV4/edit#gid=0

**Comment by wakystuf** [comment]
Updated with proposed changes (thanks, @Arpharnator  for listing all of that stuff!)
https://docs.google.com/spreadsheets/d/1A6_RSBButHJzba_oxtMq26S8GHYV_3F7QMMR6naGbq4/edit#gid=1556684404

**Comment by wakystuf** [comment]
Final version: https://docs.google.com/spreadsheets/d/11LYA0B771jnBENUrLHcifbdWTWQjNeAegDv-T8N7i5Y/edit#gid=815232167
