### ISSUE TITLE
1.4 minor changes chaos

### ISSUE THREAD

**Issue by Doruk-Coskun** [wakystuf/ESG-Mod#548]
Craver Behemoth Module is buffed. Damage and critical hit chance stats are increased to 5% -> 10%, morale effect buff is increased  5% -> 25%. Also craver behemoth module critical hit chance UI element was fixed to point out that it buffs Fleet Critical Chance.

Sophons engine health and vision range is nerfed to be align with Vodyani quest engine module. Vision range reduced by one, health reduced to 125 -> 50.

Remains curiosity appear chance increased, rewards are reworked.

**Comment by wakystuf** [comment]
@Doruk-Coskun the remains rewards look like they are generally buffed, right? For that I don't think we need to list them all, but I'd like to at least say buffed vs nerfed vs something else

**Comment by Doruk-Coskun** [comment]
@wakystuf loot reward of the remain curiosity is increased. Chance of remains anomaly or curio appearing increased.

**Comment by wakystuf** [comment]
@Doruk-Coskun OK, thanks. I've now linked both pull requests and listed this issue again as Needs Documentation

**Comment by Doruk-Coskun** [comment]
@wakystuf it appears I have actually written everything changed in the merge. I don't feel like there is anything more to add. Is there anything specific you require me to add:?

**Comment by wakystuf** [comment]
@Doruk-Coskun This Issue actually has 2 linked pull requests. 1 of them is now all set, but the other one I think has no documentation at all unless I missed it. I'll also ping you on that pull request so that you can find it

**Comment by Doruk-Coskun** [comment]
1- UE first quest search curiosity path quest requirement reduced 7 -> 5 curio search.
2- Hopeless battle tactic limit for a single flotilla is increased to 20 -> 25 CP
3- Slight nerf on T4 white plating module, Slight buffs on faction specific UE and UF t4 plating modules.
4- Blue plating health bonuses reduced.
5- Boarding pod damage overtime values and boarding pod salvo health has been reduced across the board to compensate for the reduced base manpower capacity on ships.
6- Scout and colonizer base manpower values have been reduced to 30, small attacker and protector base manpwoer values have been reduced to 60, Medium hunters and coordinators base manpower values have reduced to 150, Large carrier base manpower values have been reduced to 450.
7- Sophons Quest buildings Culture Jam Centers and Whapster are not unique buildings anymore. Their cost and effects have been adjusted accordingly.

**Comment by Doruk-Coskun** [comment]
More will come

**Comment by Doruk-Coskun** [comment]
8- Tier 4 plating defense module values have been slightly tweaked. Unfallen and UE unique versions have been buffed slightly.
9- Riftborn Empire Dev T4 Unique building effect is buffed from +15 -> +25 initial dust per turn and +25 dust increment per turn on fast. Industry cos is reduced.
10- Multimind Combat Defense Unique building strategic cost is reduced to 50 -> 30 purple in accordance with the other Adaptive Fleets Unique.
11- Daily Slogans Effect is buffed to +10 -> +15 Food per turn on outposts.
12- Moon Base dust and science yields per moon on system has been increased to +50 -> +75
13- Industry to Dust and Industry to Science conversions have been substantially buffed. T3 conversion rates are 25% -> 50% and T5 conversion rates are 50% -> 75%. Lumeris and Sophons conversion rates are buffed to 75% -> 100%.

**Comment by Doruk-Coskun** [comment]
@wakystuf these should be all

**Comment by wakystuf** [comment]
@Doruk-Coskun Thanks for these
For this one, which building is it again? I couldn't find it in the code but maybe I missed it. "12- Moon Base dust and science yields per moon on system has been increased to +50 -> +75"

Also it looked like there were these 2 other changes that you hadn't listed, right?
* Base protector and hero ship health increased to 3000 and 3500 from 2500 and 3000
* Vodyani juggernaut module locked to be only 1 per ship

**Comment by Arpharnator** [comment]
hero ship health didn't get increased at all, not sure what he's on about
Protector health is like 3600 with bonuses, with a base 3000

**Comment by Arpharnator** [comment]
also hero ship health is still like 1250 or something

**Comment by wakystuf** [comment]
Then how do you explain these?

`<SimulationDescriptor Name="ClassSectionCoreSmallSupport" Type="ClassSectionCore">
    <Modifier TargetProperty="MaximumHealth" Operation="Addition" Value="3000" Path="ClassSection"/>
  </SimulationDescriptor>

  
  <SimulationDescriptor Name="ClassSectionCoreHeroAdmiral" Type="ClassSectionCore">
    <Modifier TargetProperty="MaximumHealth" Operation="Addition" Value="3500" Path="ClassSection"/>
  </SimulationDescriptor>`

**Comment by Arpharnator** [comment]
you should check in game, I've seen it in the code and I've yet to see it work

**Comment by Arpharnator** [comment]
like, not working whatsoever

**Comment by Arpharnator** [comment]
dunno why
