### ISSUE TITLE
Add Empire Improvements to the Tech Tree

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#552]
There are 4 Steps to this:

- Put empire improvements on techs with only one item on them
- Put empire improvements that slowly increase the base stats of planet types on lacking techs with 2 items on them
- Give sophons strong versions of these empire improvements
- Give nakalim empire improvements that provide BIG immediate boosts that last for only a few turns

**Comment by wakystuf** [comment]
Updated proposal from Cobbs and myself (names refer to the tech receiving passive bonus):
* SLC Systems: Unlocks Arcological Administration [also move Auton Admin here]
* Exa-Volt Beam Focus: -10% Building Upkeeps
* Dust Micro Loans: +25% Mercenary Base Health, +3 Mercenary Move
* HyperPACs: +0.5 lux deposit value on outposts (non-outpost factions get +0.25 on colonized lux deposits)
* Adaptive Colonies: +25% PlanetInitialFIDS
* Pev-Scale Accelerators: -50% outpost action cost (non-outpost factions get +3 move on their equivalent ships. UC gets -50% cost on Transmigration Beacons)

Thoughts?

**Comment by Arpharnator** [comment]
Don't move Auto Admin, make it so it's a choice between the 2 as to which you get first and because I don't wanna have to deal with the overcol building not on the overcol tech
Don't add improvements to add improvements, the 10% building upkeep means fuckall and has no reason to exist
Same reason for the mercenary stuff, alongside the fact that what's prolly going to hapen is that I sell my ships and buy them back and now they have an extra 25% health and 3 move so nonono
Not sure why Hyperpacs needs to exist, doesn't make sense
Same for Adaptive colones, we don't give free stuff
Same for Pev-Scale Accelerators, literally no point

**Comment by Arpharnator** [comment]
all in all I'm saying to simply never think again about these empre improvements except Arcological Administration

**Comment by captaincobbs** [comment]
Astounding, every part of your opinion was wrong

**Comment by captaincobbs** [comment]
Astounding, every part of your opinion was wrong

**Comment by Arpharnator** [comment]
say why

**Comment by wakystuf** [comment]
OK, I won't code any of this until we get to more of a consensus.

@Arpharnator is your suggestion that we do not add any passive bonuses to the tech tree? I just want to make sure I understand

**Comment by wakystuf** [comment]
Updated (compromise) proposal:
* Perform the buffs on HyperPACs, Adaptive Colonies and Pev-Scale (since the first 2 of those techs are shit and the third is clearly inferior to its peers), and add Arcological Admin
* No other changes

OK with everyone?

**Comment by wakystuf** [comment]
@captaincobbs @Arpharnator 
I'll probably go ahead and code the compromise version tomorrow unless someone yells at me. I'm also happy to make adjustments though if you guys agree on something else--just let me know.

**Comment by captaincobbs** [comment]
Dust Micro Loans is one I would also like, I have a way to avoid selling your own ship and buying it back abuses.

**Comment by wakystuf** [comment]
Oh, cool. I'm fine with that then; I'll leave it for you for work that magic on

Also, doesn't ship buying/selling also lock the blueprint so that you can't retrofit it anymore?

**Comment by captaincobbs** [comment]
Yes, but I guess you could retrofit it beforehand.

**Comment by wakystuf** [comment]
Sure sure, but once you do that then it's locked forever
