### ISSUE TITLE
Federation Rework

### ISSUE THREAD

**Issue by Doruk-Coskun** [wakystuf/ESG-Mod#566]

**Comment by wakystuf** [comment]
Proposal: Federation to have bonus per hero removed. To offset, it is to receive:
* Modest buff from -25% to -33% SD cost
* +2 overcol at base and 2x effect of overcol cap techs
* No disapproval from out of power political parties

**Comment by captaincobbs** [comment]
Oh, the more efficient colonization was cut? sad
