### ISSUE TITLE
Chaos fucking documented (mostly) everything he promised

### ISSUE THREAD

**Issue by Doruk-Coskun** [wakystuf/ESG-Mod#568]

**Comment by wakystuf** [comment]
@Doruk-Coskun Get some sleep, Chaos. But after that :) :)

**Comment by Doruk-Coskun** [comment]
I will I will. when the shits are done

**Comment by Doruk-Coskun** [comment]
* Vaulters final quest where the OPBOT is required to orbit Auriga 2.0 hero level requirement is reduced 10 -> 9 which means OPBOT can be instantly used rather than needed to level up once.
* Tier 3 Cloaking module is Hero skip only now.
* Base manpower defense against enemy weapons % of defense modules is increased 5 -> 10%. In accordance with this change Red plating. manpower defense against enemy weapons % is increased 15 -> 20%
* Manpower deployment limit, manpower capacity and health values of lower tier invasion modules have been slightly reworked to reflect their tiers better. Most notably tier 1 invasion module uncloked with Shipyards provides 50 -> 100 additional manpower and 25 -> 50 manpower deployment limit.
* Argosy now starts with 8 -> 5 additional vision range and +3 vision range is unlocked with argosy upgrade tech.
* Vaulters Unique improvement (Unlcoked with tier 4 empire dev tech )strategic cost is reduced, and is no longer a unique building.
* Adaptive Fleet (T5 fleet exp unique) cost is reduced and strategic cost reduced 50 -> 30 Purple in accordance with the multi mind combat unique in the same tier.
* Vaulters second starting party is changed Military -> Religious in accordance with the political opinion of the vaulter starting minor (sisters of mercy).
* (OUTDATED) vaulters t4 science portal upgrade has the effect of 0.1 science per manpower on the system.
* Bereaved and Foundlings population collection bonus required pop numbers have been reduced 5/10/20 -> 3/5/10 in accordance with the time the pop is acquired.
* System Development Upgrades now cost industry rather than fixed turn count. Industry cost can not be displayed on the UI but each tier 1 luxury increases the industry cost by 25, each. tier 2 luxury increases the industry cost by 75 and each tier 3 luxury increases the industry cost by 150.
* Vaulters economy quadrant t2 portal effect buffed to provide 50 manpower per turn.
* Vaulter science quadrant portal effect which repairs ships increased to 25%
* Vaulters empire dev quadrant t4 portal effect now also provides 50 influence
* (OUTDATED) some changes to golden age effects, colonization turn effects etc all outdated.
* Dictatorship senator effect multiplier is increased x1.5 -> x2
* Number of active law slots increase for other parties than democracy has been reverted.
* Bereaved and Foundlings pop collection effects have been buffed. Dont make me write them all pls.
* Vaulter pop collection 2 effect now provides +500 damage done to attacker per strategic resource on the system.
* Sisters of mercy pop collection bonus 2 buffed to 50% fleet regeneration bonus. Pop collection bonus 3 buffed 25 -> 35% ground battle defender troop health.
* Vaulters final quest node Auriga 2.0 slightly changed.

**Comment by wakystuf** [comment]
@Doruk-Coskun I think this covers mostly everything. 2 questions:
1) In the code it looked like there was also some change to the Vaulter golden age max? From 15 to 20, then back to 12? What was that?
2) We don't need to list all the changes to Auriga 2.0, but can we at least clarify generally? Like was it adding/removing resources, or something else? Buff or nerf?

**Comment by Doruk-Coskun** [comment]
@wakystuf 
1- True that, I reduced the golden age duration, at the time it was to compensate for the increased golden age FIDS. TBH golden age recharge cost and duration changed so much afterward I don't know whats the latest. 

2- So auriga 2.0 starts with 4 strategic resources on them (Vanilla). I made sure all of those 4 strategic are spread to 4 planets so that each planet has a strat source. Its a buff but hard to explain

**Comment by Arpharnator** [comment]
chaos made the system fucking broken

**Comment by wakystuf** [comment]
@Doruk-Coskun OK I'll list as "Reallocated strategic resource deposits on Auriga 2.0 to have 1 deposit per planet"

For the golden age stuff, you need to figure it out, man! I don't think anyone else has messed with that, unless I'm forgetting a change from Cobbs.

**Comment by wakystuf** [comment]
@Doruk-Coskun

**Comment by wakystuf** [comment]
@Doruk-Coskun If we finish 1.4.1 before you finish documenting 1.4 I will code some random Vodyani buff that you will hate
