### ISSUE TITLE
Ramscoop Quest doesn't work with certain vision giving faction traits

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#594]

**Comment by NoProblemWithThisAcc** [comment]
The expensive 40 point trait that reveals every node with a planet doesn't notice you have 4 planets discovered outside your constellation for the ramscoop quest. (it starts at 0 even when you have vision of like 90).

If you go visit nodes you can already see, this doesn't help, forcing a very long distance to discover a nebular or something your trait didn't already give vision.

**Comment by wakystuf** [comment]
I believe the quest is regarding discovery of new systems, so I doubt this is fixable

**Comment by wakystuf** [comment]
Closing since I don't think this is fixable. If anyone else knows how to fix it, then feel free to reopen
