### ISSUE TITLE
Add a constructible (with citadel as a pre-req) which blocks singularities

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#601]
Should be tied to a T4 or T5 citadel tech, but be quite cheap to build, so that a player can demolish one if they change their mind (ex: if they make an alliance with the RB player) and/or rebuild it

**Comment by captaincobbs** [comment]
Subgoal (Ignore if deemed too hard/not possible): Hide on techtree if no riftborn are in the game

**Comment by wakystuf** [comment]
Pretty sure this one is impossible, but I linked the busted pull request in case anybody wants to give it a shot. I WAS able to create a new type of singularity which can only be built if there's a citadel, and was not linked to the RB affinity, but the problem is that there's no mechanism to actually click to "deploy" the singularity on that (or any) system if you aren't RB.

**Comment by wakystuf** [comment]
Reopened in case @captaincobbs is able to work some magic

**Comment by wakystuf** [comment]
Update (more failure):
* Assigning a time-bubble related tag to a system (ex: through force-feeding the tag using a hacking program) accomplishes nothing
* Assigning a time-bubble related simulation descriptor to a regular constructible only causes the new building to add 1 of those singularities to the empire's stock, and has no impact on the system that built the building
