### ISSUE TITLE
System Improvement Text Note

### ISSUE THREAD

**Issue by NoProblemWithThisAcc** [wakystuf/ESG-Mod#607]
The flavor text for the system improvements should let casual players know the "1 turn" part is a lie. Something like "NOTE: This improvement does not cost 1 turn! The real cost is 25/50/150 industry"

**Comment by wakystuf** [comment]
@captaincobbs Is this one fixable? I'm not sure if it is, but can we either tweak this or (if it's impossible) then reject and close it? I'll leave open for now, since I'm not sure if it's doable or not

**Comment by captaincobbs** [comment]
It's definitely possible, just override the description since the tooltip is manually created by the game
