### ISSUE TITLE
Rework Previously-ignored T4 Empire faction-specific buildings

### ISSUE THREAD

**Issue by ThanosDeGraf** [wakystuf/ESG-Mod#612]
First, be on the same page:
- "Cathedral of the Swarm" is a Unique System Improvement for Factions with the Craver Affinity 
- Is unlocked through the T4 Empire Development "Insectoid Translation"
- Costs 3120 Industry and 50 Antimatter
- Has the effect +1 Approval per Number of Ships in Empire

I think quickly becomes apparent what its intended use is: To keep one System Ecstatic. With how the Craver go about fleet composition, it is guaranteed to keep its approval bonus relevant on any system it is built on.

The Improvement has some problems, though. It is very costly, only a reasonably developed system or through massive dust investment can it be build within a reasonable time frame, in which systems are being depleted and you are not building ships, on that system. Then, the steep Antimatter cost. Together, there is a big opportunity cost associated with this improvement, where you could have been building more ships, improvements, or have an infinite system improvemnts.

The goal should be making this tech more appealing to research for mid to late game play, where presumably you'd be able to actually unlock it.

**Comment by Mermixer** [comment]
yeah this is legit uc autonomus administration but shit
i believe this is the last time youve touched it anyways, looking through #modupdates

**Comment by wakystuf** [comment]
Yeah, I like keeping the theme of +[stuff] per superpop. If your point is that the superpop are not a real mechanic, then we should do what is needed to fix THAT problem (but I tried pretty hard to do that with various other changes, like the MP quest reward).
