### ISSUE TITLE
Make Ships unlocked via Quest Rewards give the Hull Definition

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#646]
Already completed for Dark Matter, but not the base game

**Comment by wakystuf** [comment]
@captaincobbs I think this one is done, right?

**Comment by captaincobbs** [comment]
Quests to do:

- ExplorationQuest05
- Foreign Contaminant

Researchable minor faction ships (toggleable):

- Attackers on Deep Space Personnel
- Hunters on Deniable Operations
