### ISSUE TITLE
Remove circularity of UE influence buyouts

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#659]
Influence buyouts should not generate influence. Potentially results in infinite loop with enough buyout cost reductions (though less likely without superspuds effect, potentially still possible)

**Comment by captaincobbs** [comment]
+influence per manpower produced, not spent would be an easy fix

**Comment by wakystuf** [comment]
Yeah, that's a good point actually

**Comment by wakystuf** [comment]
Update: infl produced this way will now go directly to empire, to avoid causing a circular loop that crashes the game
