### ISSUE TITLE
AI Enhancements

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#689]
- Add method of detecting whether a faction is currently controlled by an AI
- Disallow AI factions from producing more than 5 core crackers (to prevent them from only producing core crackers)

**Comment by wakystuf** [comment]
This is done, right, @captaincobbs ?

**Comment by captaincobbs** [comment]
Not yet

**Comment by wakystuf** [comment]
I believe this is now complete, right? I'm changing to finished, but if that's not true then feel free to just change it back

**Comment by captaincobbs** [comment]
Correct
