### ISSUE TITLE
Ground Combat Changes

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#711]
### **Old proposal, look at [this](https://github.com/captaincobbs/ESG-Mod/issues/711#issuecomment-896470194) instead.**

These changes are pretty small but will fix a complaint I've had with ground combat for a long time, even after Arphar's Rework

1. Make Defensive Deployment Limit be a percentage of Maximum System Manpower, with a base 50% or something similar. 5000 System Manpower Cap -> 2500 Max Defensive Deployment. Rather than scaling it incrementally, like how Offensive Manpower does, scaling it with Defensive Manpower would make more sense, and remove the "25000 deployment limit, but only 5000 troops" thing that people have been complaining about.
2. Make Protect System force Defensive Deployment % to 100%, so you are deploying 100% of your Maximum System Manpower cap on well defended systems, but when you're low on manpower, you switch to draft.
3. Minor Factions, Pirates, and the Academy should get multiple ground battle strategies. They know how to use them, so I propose the following (knowing full well that Minors can't invade systems). 

Minors (Let minors use their collection bonus strategies, excluding Draft and Surrender)
- Full Force Forward (Offensive) - Works like Blitz, scaling bonus with Minor Difficulty
- No Going Back (Offensive) - Works like Guerilla, scaling bonus with Minor Difficulty
- Bunker Down (Defensive) - Works like Protect System, scaling bonus with Minor Difficulty
- Hold the Line (Defensive) - Works like (defensive) Orbital Bombardment, scaling bonus with Minor Difficulty

Lesser (Quest Fleets / Systems)
- Flash Strike (Offensive) - Works Orbital Bombardment but with Troop Damage Bonuses
- Engage on Sight (Defensive) - Works like Protect Systems but with Troop Health Bonuses

Pirates
- Para-Raiders (Offensive) - Low Manpower Cap, Strong Damage and Health Bonuses scaling with Pirate Difficulty
- Loot and Plunder (Offensive) - No Troop Bonuses, High Pop/Structure Damage %, Manpower Deployment Bonus, scaling with Pirate Difficulty
- Dug-In (Defensive) - Defensive Bombardment, Troop Health Bonuses, Low Manpower Cap, scaling with Pirate Difficulty
- Get Them! (Defensive) - Troop Damage Bonuses, High Manpower Cap, scaling with Pirate Difficulty

Academy
- Supply Strike (Offensive) - MASSIVE building damage, troop damage increase, scaling with Academy Difficulty
- Like No Tomorrow (Offensive) - MASSIVE Population damage, troop health bonus, lowered deployment, scaling with Academy Difficulty
- At Any Cost (Defensive) - Lowered Building/Pop protection and Troop Health, Increased Cap and Damage, scaling with Academy Difficulty
- Protect the People (Defensive) - MASSIVE population protection bonus and troop health, lowered damage and cap, scaling with Academy Difficulty

**Comment by wakystuf** [comment]
Seems good to me, but probably still remove the MP cap for pirates and minors in all circumstances, so that they don't accidentally survive by having poor deployment

**Comment by captaincobbs** [comment]
I'll set their limit to be like, 75%, so that their increased deployment strategies have some use

**Comment by wakystuf** [comment]
Ehh, I might just try to distinguish their strategies in some other way, since I think any scenario in which they don't deploy 100% of their stuff is just really annoying for a player who knows what their doing and can kill them in one shot

**Comment by Mermixer** [comment]
> like how Offensive Manpower does, scaling it with Defensive Manpower would make more sense, and remove the "25000 deployment limit, but only 5000 troops" thing that people have been complaining about.

what kind of complaint is that
do remember that in bigger/longer games 25k manpower is actually achievable now with the senator skill change
the entire idea of increasing the deployment limit to this high is so you can actually invade ppl in 1 turn
also i do believe there was the attempt to make it so manpower deployment was just 100% but its not doable anyways
if you make the manpower deployment 50% and 100% with the battle action id always draft so my system lasts 2 turns at least

> Minor Factions, Pirates, and the Academy should get multiple ground battle strategies.

do remember that privateer pirates are a thing, maybe theyre slighly less useless with that buff

**Comment by captaincobbs** [comment]
> what kind of complaint is that
It's confusing information, presenting information clearly is something I've always tried to do, and this doesn't do that.
And yes, I am aware that this means you can't deploy your entire army at once, but you're only going to not be able to do that if you use Draft. Use Draft if you are low on manpower, use Protect System if you have a lot of manpower.

**Comment by captaincobbs** [comment]
> Ehh, I might just try to distinguish their strategies in some other way, since I think any scenario in which they don't deploy 100% of their stuff is just really annoying for a player who knows what their doing and can kill them in one shot

Explain

**Comment by Mermixer** [comment]
theres exactly 2 ways that you can invade someone atm
1) you get a metric fuckton of manpower (preferrably like 50% more deployment than they have max) and oneshot the system with manpower modules
2) you get a bajillion siege modules and kill the system in 1 turn and then fight the manpower that gets drafted

for new players those are the 2 ways where they only need to discover 1 to perform ok in their games (2 is obv better bc lacking manpower feels very common atm)

the 2 battle actions purpose is draft to do some return dmg after they oneshot your system or defend system so their unprepared invasion doesnt kill you
let me reiterate, option 1 should only take 1 turn because otherwise they might just draft enough so you cant actually take the system and option 2 should only take 2 turns (or more if youre poor and cant afford siege modules but lets get real what are you even spending your green on) and in the second turn you have enough manpower to kill the draft

**Comment by wakystuf** [comment]
Yeah, Merm makes good point. The fundamental insight here is that poor defensive deployment can help the defender prolong a battle that they are certain to lose eventually (even though yes, it does mean that the defender will do less damage overall and be less likely to WIN). It is still better for the defender to lose slowly than to lose quickly, if they are doomed. And usually, the defender is indeed doomed, since the attacker won't choose to invade unless they are likely to win.

Therefore, I would suggest we avoid anything that results in the defender deploying less than 100% of their MP in one turn.

**Comment by captaincobbs** [comment]
I see, let me rewrite some stuff then

**Comment by wakystuf** [comment]
Here's one quiz to further illustrate the point. Question: if you have a well-defended system with lots of defensive MP vs a huge invasion fleet (NOT a siege fleet, but an invasion fleet with a billion deployment and MP), what is the best defensive battle tactic?

Answer (insanely): Stampede. You're doing to die no matter what, so might as well guarantee that only half of your dudes die in the first turn, which gives you a turn to react, and then the other half will die the next turn.

I'm half-joking about this, but if we want to make "Protect System" actually useful, you could make it always deploy -50% of the system's MP, so that the system will be guaranteed to survive for 1 turn. I would probably not do that, however.

**Comment by captaincobbs** [comment]
Ok, new proposal.
1. Deployment Limit will be 100% of Manpower Capacity
2. Protect System will lower Deployment by 50% (or something similar)
3. Minors, Lesser Empires, Pirates, and the Academy will still get new strategies, but they will be modified:

Stampede - Changed to -25% Damage and -25% Health (instead of lowered deployment)

Minors (Let minors use their collection bonus strategies, excluding Draft and Surrender)
- Full Force Forward (Offensive) - High Deployment, Increased Health, Bombardment Vulnerability scaling bonus with Minor Difficulty
- No Going Back (Offensive) - Low Deployment, Increase Damage, Bombardment, scaling with Minor Difficulty
- Bunker Down (Defensive) - Lots of Health Bonuses, lowered Improvement Destruction, scaling bonus with Minor Difficulty
- Hold the Line (Defensive) - Damage Bonuses with Defensive Bombardment, scaling bonus with Minor Difficulty

Lesser (Quest Fleets)
- Flash Strike (Offensive) - Orbital Bombardment but with Troop Damage Bonuses
- Engage on Sight (Defensive) - Works like Protect Systems but with Troop Health Bonuses

Pirates
- Para-Raiders (Offensive) - Health and Damage Bonuses, Low Deployment, scaling with Pirate Difficulty
- Loot and Plunder (Offensive) - High Bombardment, High Deployment, scaling with Pirate Difficulty
- Dug-In (Defensive) - High Health Bonus, Low Damage Bonus, scaling with Pirate Difficulty
- Get Them! (Defensive) - High Damage Bonus, low Health Bonus, scaling with Pirate Difficulty

Academy
- Supply Strike (Offensive) - MASSIVE building damage, troop damage increase, lowered deployment, scaling with Academy Difficulty
- Like No Tomorrow (Offensive) - High Deployment, Lowered Health, scaling with Academy Difficulty 
- At Any Cost (Defensive) - Increased Population/Improvement Destruction, Greatly Increased Damage, Bombardment Damage Scaling with Academy Difficulty
- Protect the People (Defensive) - Bombardment Resistance, Lowered Population Destruction, Increased Health, Scaling with Academy Difficulty

**Comment by wakystuf** [comment]
This all sounds good to me, except that I was mostly joking about Protect System. It could work, but could also just be annoying (basically totally prevents one-shotting a system). Maybe set it at like the greater of -50% and [insert big number], like 10k or something? That way at least some shitty system with like 400 MP can't troll you by deploying only 200. Even then it might be too much of a change, however.

**Comment by captaincobbs** [comment]
As in, only deploy half manpower if above X?

**Comment by wakystuf** [comment]
Yeah. That way being able to delay for 1 turn is a reward reserved for those who prepare good defenses (IE, cap over X). X=10k seems like a reasonable place to start, but hard to say.

**Comment by Mermixer** [comment]
if the man is able to put 20k manpower into their invasion fleets then he should be allowed to oneshot systems imo

currently systems that have 20 pop can easely go over 2k manpower with only the hero skill on empire, once you start building manpower buildings you will struggle to fill yours until the effective end of the game

**Comment by Mermixer** [comment]
then again i suppose siege fleets are much better than invasion fleets anyways so who cares

**Comment by Arpharnator** [comment]
protect sysstem isn't useless, it's just that usually there is no mp to % health increase because of siege. Changing it this way only accomplishes what I believe the current protect system is doing, which is prolonging the system health against invasion fletrs.

**Comment by captaincobbs** [comment]
It doesn't do it effectively enough to warrant not using draft 90% of the time

**Comment by Arpharnator** [comment]
as far as I know draft is like 150 mp, and as such using rptect system becomes worthwhile at around 600 mp, or a bit more like 1k depending on upgrades. Draft is always used because siege fleets deplete the mp so can't use protect system on a system with 0 mp

**Comment by captaincobbs** [comment]
Why tf is ground combat in this game so terrible

**Comment by Mermixer** [comment]
otherwise it would be fun

**Comment by captaincobbs** [comment]
Don't want to do this anymore, too much work

**Comment by captaincobbs** [comment]
Superseded by #1020
