### ISSUE TITLE
Garrison Changes

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#714]
We talked about this early 1.4.1 and it was accepted, but we agreed to do (numbers aren't final):

- Ship Upkeep will scale with their level (same percentage as the shield / health increase)
- Garrisoned Ships have -50% Upkeep, but increased upkeep overall (per level)
- Garrisoned Ships have +2% health regen (40%)
- Rejuvenation Field heals 100% per turn

**Comment by wakystuf** [comment]
Update: 
* Ship upkeep already did scale with level (I coded that back in 1.4)
* Garrisoned ships now have -50% upkeep
* Garrisoned ships have +20% health regen
