### ISSUE TITLE
Difficulty Changes

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#716]
Move Arphar's difficulty changes to new settings (localization for these was already made in 1.4.1), remake the old difficulties how they are.

Expected changes: Academy, Minor, and Pirate difficulty should each have a higher difficulty level.

Main worry: it may not be possible to make a new difficulty level, if so, skip this.

**Comment by wakystuf** [comment]
@captaincobbs can you clarify for @FluffiestPrincess what you were hoping to achieve here? Is the idea to make the current "Hard" relabeled as "Endless" and then create something for minors and pirates that is similar to the current Hard except without Arphar's much-more-lethal ship designs?

**Comment by wakystuf** [comment]
I took care of this one; didn't add a new setting, but just got rid of Easy (since we effectively have with our other changes to the underlying function) and shifted everything up one, including a new Endless at the top

**Comment by captaincobbs** [comment]
Can you elaborate on what you've done

**Comment by wakystuf** [comment]
Old labels: Easy, Normal, Hard
New labels: Normal, Hard, Endless

No change to gameplay, other than the recommended settings will now push to the middle settings (Hard)

**Comment by captaincobbs** [comment]
Ah, I don't really think this issue is finished then, the point was to fix some of the bugs and add back the classic difficulties.

**Comment by wakystuf** [comment]
I wasn't aware there were actual bugs; what are those? 

Adding back the classic difficulties would probably be adding an Easy, which is way more work. I'll just mark it open and unassign myself in that case.

**Comment by Arpharnator** [comment]
I might take up on adding a new difficulty at some point

**Comment by Arpharnator** [comment]
Made new difficulties and removed hard, however small issue with localisation despite having GUI elements and localisation
![image](https://user-images.githubusercontent.com/49691625/212475981-d7802e1e-94bf-4968-a24d-f97d2abd83cc.png)

**Comment by Arpharnator** [comment]
![image](https://user-images.githubusercontent.com/49691625/212476016-b28290be-e29c-445c-83f3-f6787ea1c666.png)

**Comment by wakystuf** [comment]
Looks good. I see the bug. I'll push a fix in a moment

**Comment by captaincobbs** [comment]
What do the new difficulties entail?

**Comment by Arpharnator** [comment]
impossible is more or less old hard and endless is for people with a deathwish

**Comment by captaincobbs** [comment]
Completed and finally working as intended, just needs documentation
