### ISSUE TITLE
Terraformation Changes

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#718]
Pyrophobic, Cryophobic, and Petraphobic get their own terraformation techtrees and colonization orders.
Cryophobic's T0 planets are the planets with the Hot tag, and research will start off with the temperate ones and work its way to cold
Pyrophobic's T0 planets are the planets with the Cold tag, and research will start off with the temperate ones and work its way to hot
Petraphobic's T0 planets are gas planets, and research for colonization order will otherwise be similar to riftborn.

Tie immunity to having a T0 planet colonized without having the tech to the trait (Biophobic, Pyrophobic, Cryophobic, and Petraphobic all need this), whereas Fertile T0 immunity should otherwise be the default.

This is the only thing I plan on doing in 1.5

**Comment by wakystuf** [comment]
Duplicate, rejected

**Comment by captaincobbs** [comment]
No no, straight up delete it, not close
