### ISSUE TITLE
Add malus for buyout of Wonders

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#733]
50% premium applied to buyout cost only for Wonders. May not be doable, but will try.

**Comment by wakystuf** [comment]
Put on hold for now. May never happen.

**Comment by wakystuf** [comment]
I tried on this one, but I don't think it's possible

**Comment by wakystuf** [comment]
Resurrected from the ashes; I found a new variable that makes this one possible now. Complete, using the 33% originally agreed with Chaos.

**Comment by captaincobbs** [comment]
Why though

**Comment by wakystuf** [comment]
To penalize the silly super-early buyout of wonders in general. Still doable, but less efficient

**Comment by Provolonage** [comment]
honestly if it made malus higher we might be able to buff wonders into mattering again, the current meta is seeing zingy buy park on turn 9-11 or if he's not there iter being built before park most times since its just not worth the early tempo on most factions.

**Comment by Mermixer** [comment]
yeah but the issue with zingy buying it out turn 10 is also related to the fact that he starts building it turn 5
so it wouldnt rly fix it would it
