### ISSUE TITLE
Kill Ramscoop and Rework Seek the Unique

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#745]
Replace the Ramscoop with...literally anything else, but rework the quest & rewards so that it can be re-enabled (make it no longer tied to the academy quest setting)

**Comment by Mermixer** [comment]
3 speed 5 evasion?
3 speed 1 vision range?
3 speed ~100 health?
any of those, but at least 20 indy
maybe even a rather expensive one but 4 speed?

**Comment by wakystuf** [comment]
Yeah, those are good ideas. I think ideally it'd be more exploration themed than combat themed. So probably either 30 cost and 3 speed/1  vision or 50 cost and 4 speed (no other bonuses).

Then we'd also need to figure out what to do about the parts of the quest too, like replacing that probe microfactory module that is just inconceivably bad.

**Comment by wakystuf** [comment]
Update: 4 move on Ramscoop but no other effect (and still more expensive than most engines)
Probe microfactory effect replaced with +5 vision range instead (I know, it's a lot, but will anybody actually pick it vs a 4-move engine? Anyone?)

**Comment by wakystuf** [comment]
Update: also fixed bug where the vision module questline would also unlock the ramscoop. Bug internal to 1.5 so no documentation required
