### ISSUE TITLE
Mildly increase resource spawn on market

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#747]
auto spawn already exists, just make the algorithm that causes it a little bit smarter

**Comment by wakystuf** [comment]
Update: tried to do this one and couldn't seem to make the resource gen events trigger. Giving up for now. Maybe it is possible, but I couldn't figure it out.

**Comment by wakystuf** [comment]
I think I have finally figured this one out; I'll be resurrecting a very old branch to make this happen and incorporate with some other market changes I recently figured out

**Comment by Arpharnator** [comment]
might want to tweak the resource gen to happen every few turns instead of every turn if possible, perhaps with only a few resoures at the same time.

**Comment by wakystuf** [comment]
Sadly, not possible. I get one number, and that's it. The market is really hard to mod
