### ISSUE TITLE
Horatio Splicing Changes

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#760]
@Arpharnator can you please list the changes you made to the splices? I think that was it aside from the (reverted) changes to the splice formula, right?

**Comment by Arpharnator** [comment]
bettered

**Comment by Arpharnator** [comment]
list is long and incoherent because of the way the assimilated simulation descriptors work with the pop yields so cba

**Comment by Arpharnator** [comment]
and what are you gonna do with it anyways

**Comment by wakystuf** [comment]
I was going to put it on the changelog like everything else! I'll just document as follows:
Splice bonuses increased by ~+1 of respective resource on average

**Comment by wakystuf** [comment]
Update: I'll revisit the numbers on the quest and hero stuff in light of the 50% lower splice cost
