### ISSUE TITLE
Replace Craver "ignore forced peace" quest reward with -50% terraform cost on sterile to sterile

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#763]
Will only affect these terraform options (which are the ones that most impact happiness):
* Lava to Ash
* Lava to Desert
* Ash to Desert
* Barren to Ice
* Ice to Arctic
* Barren to Arctic

**Comment by captaincobbs** [comment]
Cravers are lore-wise bad at terraformation, I don't think this is a great idea for that reason.

**Comment by wakystuf** [comment]
Haha OK. I'm so down to reject this, since I was dreading coding it anyway.
