### ISSUE TITLE
Dictatorship Buffs

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#771]
With the other govt changes, Republic, Federation and Democracy should be roughly balanced. Non-Craver dictatorship still lags a bit, however, so Cobbs and I propose 2 buffs for (non-Craver) dictatorships:
* Double-frequency elections
* Double action points on fleets

Thoughts? We will need to confirm that the game doesn't explode when we mess with those 2 variables, by the way, as they are unusual to mess with.

**Comment by Arpharnator** [comment]
While the double frequency for elections is not a bad idea it also means that you are supposed to have the inf to use the laws or change party regularly, which not something that I believe is good for the former since it would simply be a placebo buff and if you decide to switch I guess it could work but it would still be pretty shit unless hissho

**Comment by Arpharnator** [comment]
the problem stems from both law enaction costs as well as law upkeep and there's also the fact that I don't like borrowing from other governement types (ie democracy)

**Comment by captaincobbs** [comment]
I see what you're saying, but Democracy doesn't have lowered enaction costs, so it wouldn't be duplicated.

**Comment by Arpharnator** [comment]
but then there is still the problem of upkeep, it is impossible to run a T4-T5 law turn 15 for more than 1 turn

**Comment by captaincobbs** [comment]
That's their problem

**Comment by wakystuf** [comment]
Yeah, Arphar makes a good point, though most of the dictatorship factions are decent at influence (Hishso, Horatio, Cravers), right? Also, this will give them earlier access to the independent laws that don't cost influence.

Is there a change you would like us to incorporate into this, Arphar? I'm open to doing that, since I think you raise a fair point.

**Comment by wakystuf** [comment]
Update: based on suggestion from Provo, the action point bonus is to be converted into +50% hero XP on governors
+1 action points to be moved to a tech instead (probably High-Energy Magnetics)

**Comment by wakystuf** [comment]
Update: Election frequency effect also applies to Cravers
