### ISSUE TITLE
Craver Changes

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#779]
Pasting what I wrote in the senate

OK, I thought a bunch more about this Craver stuff and have an actual proposal, which I think is thematically designed to accomplish the same goals as what Chaos said: a)  making depletion a real mechanic b) thematically making the Cravers a  consuming horde that devours progressively more of the galaxy, c) maintaining approximate balance-neutrality, d) making pop collection III not shit, e) making the quest reward not shit
First point is that I would separate the quest reward from the pop collection III initially, and we can take each of them in turn.
We can fiddle with the numbers; I'm going to list each of them with a range on purpose
1) Pop Collection III: Buff to +X approval on Empire per depleted planet in Empire (X of 1.5-3)
This is the most important part, as it enables them to deplete a place, and then overcol to find a new place. +3 would mean a fully-depleted 5-planet system fully "pays for" its approval penalty due to overcol, and 1.5 would mean it halfway "pays for" itself
That btw, I think is big buff. The rest of these are thematically-related nerfs
2) 2a) As Chaos already said, lower depletion cap on planets -X% (X of 20-33%
2b) Probably should also try to narrow, but not remove, the variation by planet size to avoid increasing the RNG sensitivity of the Cravers. So Huge will be reduced much more than Tiny, which will be reduced only a little bit
2c) Do whatever is needed to offset for Husk, so that it's roughly the same # of turns until depletion as before (so prob means starting it off with fewer depletion points)
3) Craver base pop +X more likely to increment (2-3x), as if it is always "boosted" with a lux (and then gets boosted even more with a lux)
This I think reduces the issue Chaos was worried about with lots of non-slave pops, but it's not nearly as harsh as drastically whacking the FIDS of non-slaved minors. It also provides the Cravers more incentive to use the Enslave action or otherwise go conquer more non-Craver pops if they want them
4) To avoid accidentally buffing the Craver strat/lux economy, depleted planets generate only X% (0-50%) strat or lux resources
[end of part with Pop Collection III]
5) Now for the quest reward, I would do 1 of Chaos' ideas: either add the recycling effect, or simply move the old pop collection III bonus onto the quest reward instead (I would do ONE of those 2 things, but not both--not that anybody is suggesting both. Just clarifying)
6) I would then apply some non-trivial but not huge nerf to offset. My suggestion would be +X% dust upkeeps on fleets (X fairly sizable though, not like 10%). 
I'm also open to other ideas for the nerf, but ideally would cover these 2 themes: a) fleet related, but b) not significantly harm their combat performance (I think like a -X% damage or health is inappropriate, for example)

**Comment by captaincobbs** [comment]
I really think making the collection bonus be approval defeats the point of depletion. As you deplete planets, your military strength should rise, and your economy should fall. But extra approval only encourages economy.
