### ISSUE TITLE
Increase starting infl to 15

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#780]

**Comment by captaincobbs** [comment]
Just curious, how come

**Comment by wakystuf** [comment]
It was Chaos' idea. He didn't say why, but I'm assuming that it's caused by the law rework and wanting to make sure that people can use the new tier 2 laws on turn 1. Though actually 2 x 3 x 3 = 18 (tier 2 law x 3 pop = upkeep of 6, and passage is 3x upkeep = 18). So we might need to slightly bump it again actually now that I think more about it

**Comment by Mermixer** [comment]
something something not being able to use t2 law as sophons on turn one, even though hed switch to the t1 law on turn 2
