### ISSUE TITLE
Fix Antimatter Lock-On on quest hulls

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#784]

**Comment by wakystuf** [comment]
@captaincobbs Do you know how to fix this one? I'm not sure I know where to find them in the code

**Comment by captaincobbs** [comment]
What's wrong?

**Comment by wakystuf** [comment]
I'm told that the quests which grant the carrier hulls come equipped with antimatter lock-on, which is a coordinator-only module

**Comment by captaincobbs** [comment]
Intentional

**Comment by wakystuf** [comment]
@captaincobbs 
I think the goal here is to make it so that the Spear ships still use the lock-on as they currently do, but that when the carrier is unlocked for a player the design does NOT include lock-on. Make sense?

**Comment by wakystuf** [comment]
Fixed. The quest will now unlock a different design from the same hull, which will include only basic white modules and no lock-on.
