### ISSUE TITLE
Fix Flotilla pathing

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#79]

**Comment by captaincobbs** [comment]
Planned for 1.3.1, decided to merge with a more updated version of Combat Path Rework by Cat-O-Nine-Tails, make sure to thank them profusely because this looks terrible to code.
To be included with the combat test mod

**Comment by captaincobbs** [comment]
Delayed for further discussion

**Comment by wakystuf** [comment]
This is tagged as "finished", which is the filter I am using for posting to the wiki, but the commentary suggests otherwise. Should this have the "finished" tag removed? For now I've simply tagged as "Needs Documentation" since I don't want to mess anything else up.

**Comment by captaincobbs** [comment]
There was an issue that needed to be discussed but it seems we never got back to it

**Comment by wakystuf** [comment]
OK, sounds good. I'll remove the Finished and Needs Documentation tags in that case, if that's OK?

**Comment by captaincobbs** [comment]
The code is finished, but it definitely needs documentation

**Comment by wakystuf** [comment]
OK, great. Is this the change that gets rid of the annoying firing arcs, or something different? I can also go look at the code if needed (just tell me where to look, since I have no idea where the flotilla pathing would live)

**Comment by captaincobbs** [comment]
Yes, it gets rid of the annoying firing arcs. Good luck interpreting this, but I believe this is the file: [EncounterFlotillaMatchDefinitions.xml](https://github.com/captaincobbs/ESG-Mod/blob/combat-path-rework/Endless%20Space%20Competitive%20Mod/Simulation/Battles/EncounterFlotillaMatchDefinitions.xml)

**Comment by wakystuf** [comment]
Yeah, that makes sense. It looks like the new code is modifying the series of waypoints that are used for the parabolic interpolation of the flight paths and rotations, though it's hard for me to see precisely what the consequence would be of the various numerical changes. Is the removal of firing arcs simply an indirect consequence of the new flight paths, or is there someplace else in the code that they are bypassed?

**Comment by captaincobbs** [comment]
This is a direct consequence. The "removal" of firing arcs is directly caused by the new flight paths. We're merging with [this](https://steamcommunity.com/sharedfiles/filedetails/?id=1288116190) mod, and Cat has included some screenshots so you can understand what's happening.

**Comment by wakystuf** [comment]
Ahh, that's quite interesting. I mean this really seems like how the flotillas should've always moved from the beginning given that the additional complexity was never explained anywhere and can't be controlled by the player. I'll add to the wiki now and then mark as Documented

**Comment by captaincobbs** [comment]
I think the main issue is that the distance increase messes with DPS calculations

**Comment by wakystuf** [comment]
Yeah, the way that travel time for weapons modules works is one of the parts of combat that I still don't understand at all. Hopefully once 1.3.1 is released somebody can explain that to me

**Comment by wakystuf** [comment]
Random thought: it looks like firing arcs are defined for each weapon slot in the code. Would changing all of those numbers to "360" also solve this issue?

**Comment by captaincobbs** [comment]
no because then the ship would shoot through itself and combat would last longer than it should (the "retreat" period)
