### ISSUE TITLE
Tech Link between Machine Bacteria and both Hardship Bonus Incentives and Graviton Research has no effect

### ISSUE THREAD

**Issue by Mermixer** [wakystuf/ESG-Mod#819]
![image](https://user-images.githubusercontent.com/81304992/133587491-6112215f-9371-45c6-89fc-a087110a6017.png)
this shit doesnt work

**Comment by Mermixer** [comment]
the fucking tech link from machine bacteria to hardship incentives/ graviton doesnt work

**Comment by wakystuf** [comment]
I'm not sure what the problem is here, but I'll look into it next week once I finish with diplomacy and some other changes

**Comment by wakystuf** [comment]
Fixed. This tech link didn't actually exist, so I just cut the lying GUI element. Shouldn't have been there in the first place, which is why it wasn't "working"
