### ISSUE TITLE
Starting Resource Changes

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#824]
Move Lumeris starting dust to a faction trait
Remove extra horatio starting influence since it is no longer appropriate

**Comment by wakystuf** [comment]
I'll do the Horatio part. Not sure what the thing is with Lumeris tbh

**Comment by captaincobbs** [comment]
It's already finished

**Comment by wakystuf** [comment]
Ah, right. I should've read the tags more carefully. This is what I get for mixing drinks with friends + Github
