### ISSUE TITLE
Buff Unfallen Population Quest Weapon

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#845]
Waky, you told Provo and I that you'd do this after it came up in a conversation.

**Comment by wakystuf** [comment]
Yeah, true true; I'll take care of it, probably tomorrow.

**Comment by wakystuf** [comment]
Update: done. Effects:
![image](https://user-images.githubusercontent.com/79942510/135018361-28fabbdb-11a1-4f85-b4cd-515a1e5fb196.png)
