### ISSUE TITLE
Make Strategic Slots count for ship sell cost

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#868]

**Comment by wakystuf** [comment]
@FluffiestPrincess This one I can explain:
* Currently, the sale price of a ship is based on a combination of its TotalIndustryCost and its TotalStrategicCost (1-6 each have separate variables)
* Each module contributes to both the TotalIndustryCost and the respective TotalStrategicCost, such as the following:
    `<BinaryModifier TargetProperty="TotalStrategic6Cost"    Operation="Addition" Left="1" BinaryOperation="Multiplication" Right="$(Multiplier)" Path="ClassModuleWeapon" TooltipHidden="true"/>`
* However, the unlockable modules for each ship hull require additional strats if they are filled with modules (ex: the screenshot below requires hyperium for the slots)
* The cost of the strats used in those modules is not stored anywhere, and therefore is not included in the TotalStrategicCost or, by extension, the TradeValue

![image](https://user-images.githubusercontent.com/79942510/168722757-96d69015-7e3f-4097-a9f8-37fe7096b4dc.png)

**Comment by FluffiestPrincess** [comment]
The good news is that I can make Strategic Slots add to the TotalStrategic<n>Cost of the module in them.

The bad news is that:

1. I haven't yet worked out how to do it without creating an enormous number of new SimulationDescriptors, one for every possible strategic slot cost.
2. Increasing the TotalStrategic<n>Cost of the module doesn't seem to affect the ship's sell price at all.

**Comment by FluffiestPrincess** [comment]
It's time for Good News - Bad News again!

The good news is that I solved problem 1!

The bad news is that I don't know if I can be arsed applying a new SimDesc to 268 separate XML elements, so this is going to have to wait until either I'm really bored or I decide to write a script to do it.

**Comment by wakystuf** [comment]
@FluffiestPrincess Is this still active?

**Comment by captaincobbs** [comment]
Not worth the effort, closing.
