### ISSUE TITLE
Change ratio religious quest 1st chapter to require 50 luxuries, not currentLuxes+50

### ISSUE THREAD

**Issue by Arpharnator** [wakystuf/ESG-Mod#886]

**Comment by captaincobbs** [comment]
how come, are you malding

**Comment by Arpharnator** [comment]
just something that annoys me since quest pops on turn 3 and sometimes you can get like 10 or 15 luxuries

**Comment by wakystuf** [comment]
Yeah I wouldn't mess with that, I don't think. X+50 still doesn't seem that hard, especially for a faction with a good explorer, right?

When does Horatio typically get markets? Is it viable to buy a bunch of [whatever is cheap af]?

**Comment by NoProblemWithThisAcc** [comment]
> make the other 2 much easier making this easier might as well not even have a lux requirement

Yes make the others easier. I seem to always do that quest early and sometimes 50 takes a very long time. Other times RNJesus blesses me and I am making a ton of the strat needed.
