### ISSUE TITLE
Nerf temporal drag to 25%

### ISSUE THREAD

**Issue by Arpharnator** [wakystuf/ESG-Mod#894]
Based on testing done with merm we saw that 1) flak was not good at preventing losses and killing the bomber coordinator fleet, WITHOUT temporal drag, and the result with it was desastrous.
2) temporal drag reduces dps of normal weapns by 33%, and no equivalent exists for bombers, alongside the fact that bomber do not get rekt by their mothership getting destroyed, only by them taking direct damage meaning that so long one ship is alve it can wipe the floor with enough bombers

**Comment by wakystuf** [comment]
Incorporated within the combat changes just posted, so I'm going to close this one
