### ISSUE TITLE
Rebalance UC Beacon Special Node Effects

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#901]
Proposal, very much open to thoughts, particularly on calibrating the numbers:
* Nebular Clouds: Nerf from 7.5% evasion to 3%
* Black Hole: No change to move effect
* Solar nebula: Replace upkeep reduction with +10% shield capacity
* Asteroid field: Replace retrofit cost reduction with +10% health
* Collapsing star: Replace XP effect with +5% crit chance
* Neutron star: Replace vision range with +7.5% accuracy
* Rejuv field: Buff regen from 5% to 50%

**Comment by captaincobbs** [comment]
🤔
