### ISSUE TITLE
Make deposit value improvements scale with game speed

### ISSUE THREAD

**Issue by Provolonage** [wakystuf/ESG-Mod#908]
Strat deposit values from improvements don't scale with game speed, i.e. you would make more strats on fast.

**Comment by Arpharnator** [comment]
no

**Comment by captaincobbs** [comment]
I know this was discussed in the balance senate earlier, what's the status with this

**Comment by wakystuf** [comment]
I don't think there was a definitive conclusion either way

**Comment by captaincobbs** [comment]
Should we consider this rejected?

**Comment by captaincobbs** [comment]
Provo asked me to close this for now
