### ISSUE TITLE
Minor Civ Assimilation Tweaks

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#921]
1) Replace dogshit (actively counterproductive?) Remnant Concentrated Constructors II (improvement destruction probability) with 5 dust per CP recycling
2) Nerf Galvran sci cost reduction from 10% to 5%
3) Make Behemoth Awe influence gen trait not apply to outposts

**Comment by wakystuf** [comment]
Update: also buffed Concentrated Constructors to -33%, but if Cobbs can discipline his baby plugin into working then we can implement the unique planet cost reduction instead

**Comment by captaincobbs** [comment]
Question, what was I supposed to do for this

**Comment by wakystuf** [comment]
Update: Concentrated Constructors I worked all along and I just never restarted the game when I fixed the plugin. Now it's -25% on both Wonders and Uniques
