### ISSUE TITLE
Art Changes

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#922]
1. ~~Hardened Shield Generators Recolor~~
2. ~~Final Tier Vodyani IDSI Module Recolors~~
3. ~~4D Spreadsheets (Empire Improvement) Icon~~
4. ~~Influential Traders (Empire Improvement) Icon~~
5. ~~Ransacker Module Icon~~
6. ~~Vaulters Final Quest Manpower Reward (Empire Improvement) Icon~~
7. ~~Shield Regenerator~~ (+Flat on Ship) / ~~Reloader Icons~~ (+% On Flotilla)
8. ~~Exploratory Non-Detection Systems~~ (Cloaked Explorers)
9. ~~Opulent Frontiers~~ (Luxuries on Outposts)
10. ~~Pre-Planned Unpacking~~ (+% FIDSI while within Colonization Threshold)
11. ~~Automated Prefabs~~ (+% FIDSI while within Colonization Threshold)
12. ~~Mercenary Contracting~~ (Pirate Attackers)
13. ~~Letters of Marque~~ (Pirate Hunters)
14. ~~Home-Cooked Rations~~ (Food to Manpower)
15. ~~Premium MREs~~ (Food to Manpower)
15. ~~Predictive Groceries~~ (Food to Dust)
16. ~~Advanced Culinary Tourism~~ (Food to Dust)
17. ~~Prompt Pioneering~~ (Faster Colonization / Food on Outposts)
18. ~~Environmental Optimization~~ (FIDSI on Planets)
19. ~~Applied Happiness Program~~ (Needs Approval Image)
20. ~~Vulnerability Assessor~~ (Needs Tactics Card Image)
21. ~~Tactical Expertise~~ (Needs Tactics Card Image)
22. ~~Battlefield Analysis~~ (Needs Tactics Card Image)
23. ~~Agile Command~~ (Needs Tactics Card Image)
24. ~~Lethal Squadrons~~ (Needs Tactics Card Image)
25. ~~Aurigan Expansion~~ (Use Image from the Pooster Program)
26. ~~Factory of Faith~~ (Needs Approval Image)
27. ~~Cloth of Austerity~~ (-% System Dev Cost)
28. ~~Insatiable Maw~~ (Dust per CP Destroyed)
29. ~~Artificial Hive Minds~~ (Science per CP Destroyed)
30. ~~Black Tax Authority~~ (Dust per Planet, +% Dust on System)
31. ~~Scavenger Contracting~~ (Dust per CP Destroyed)
32. ~~Safer Streets~~ (Use Image from the Pooster Program)
33. ~~Pay It Forward~~ (Industry while Ecstatic)
34. ~~Apolitical Population~~ (Buyout Reduction)
35. ~~City Planner~~ (-% System Dev Cost)
36. ~~Underground Comprehension~~ (+1 Pop Slot on Fertile)
37. ~~Studies of Those Enhanced by Dust~~ (+40% Hero XP)
38. ~~Ecosystem Perfection~~ (+15% Racial Modifier Bonuses)
39. ~~Economical Adaptation~~ (+50% Consumption, +4% FIDSI per System Level)
40. ~~Perfection of the Perfected~~ (+1 Module Multiplier on Hero Ships, +1% FIDSI per Hero Level)
41. ~~Patriotic Shipyards~~ (Troop Damage, Troop Health, Ship Cost)
42. ~~Reuse and Recycle~~ (Influence per Industry, +% Industry)
43. ~~Strategic Privacy~~ (-% Treaty Cost)
44. ~~Sensor Suite~~ (Vision Range on Ships)
45. ~~Void Familiarity~~ (Hacking Speed outside of Starlanes)
46. ~~Echo Condensation~~ (Manpower per Bandwidth)
47. ~~Happy Nappers~~ (Approval per Sleeper)
48. ~~Burning Metal~~ (Hacking Speed per Backdoor)
49. ~~Happy Haunting~~ (Approval forced to 85)
50. ~~Dispatch Engines~~ (Fidsi per Bandwidth)
51. ~~Chassis Optimization~~ (-50% Riftborn Pop Cost)
52. ~~Martial Outlook~~ (+50% Riftborn Manpower Repeatable Efficiency)
53. ~~Integrated Shells~~ (-25% Riftborn Pop Cost, +25% Riftborn Manpower Repeatable Efficiency)
54. ~~Node Analyzers~~ (Basic gives influence and dust, Advanced gives strategics)
55. ~~Relentless Assault~~ (+1 Action Point)
56. ~~Improved Commercial Drives~~ (Purple, Movement on Civilian Ships)
59. ~~Cloak II should be recolor to titanium blue~~
60. ~~EMP Disruption Field icon is messy~~
61. ~~Unfallen Heart's Ward module recolored to Hyperium~~
62. ~~Craver Unique variants of buildings need to be denoted as Unique~~
63. ~~Nakalim Unique variants of buildings need to be denoted as Unique~~

**Comment by captaincobbs** [comment]
![image](https://user-images.githubusercontent.com/16710532/142120557-9bd0cd46-1002-43cc-9f01-7c244d40bab3.png)
Recolor this icon to be Antimatter colored for EMP Disruption Field, make Disruption Field properly show up as an Antimatter Module on the tech tree

**Comment by captaincobbs** [comment]
4D Spreadsheets needs an icon
![image](https://user-images.githubusercontent.com/16710532/142717463-6b222eaf-9158-4c94-95d1-4cfc400920aa.png)

Influential Traders also needs an icon
![image](https://user-images.githubusercontent.com/16710532/142717477-f810bf2e-7c60-47aa-8599-3b637216c77a.png)

**Comment by captaincobbs** [comment]
Ransacker Module needs new art
![image](https://user-images.githubusercontent.com/16710532/142717525-5c6aba4d-81ef-4dc8-9e75-30bb71c40af3.png)

**Comment by captaincobbs** [comment]
Shield Reloaders / Regenerators need art to differentiate between them

**Comment by captaincobbs** [comment]
Keeping this open as a reminder to myself
