### ISSUE TITLE
Small Unfallen Tweaks

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#946]
Tweaks to Amblyr to match their lore:

- Replace population bonuses with +2 Industry on Temperate, +2 Dust
- Replace Investors (Pacifist -> Industrialist) political trait with Anti-Militarist

Fix Unfallen last quest not launching
Reduce cost of Unfallen quest terraformation

**Comment by Provolonage** [comment]
Yes please

**Comment by ThanosDeGraf** [comment]
> Reduce cost of Unfallen quest terraformation
Was that not changed with the Terraforming cost changes in 1.4? If not, it's only fair they get that same treatment.

**Comment by wakystuf** [comment]
Yeah I may have forgotten to change Unfallen terraforming; I don't remember. I do know that I made Unfallen initial colonization cheap af, but I think that's separate

**Comment by captaincobbs** [comment]
Split into multiple issues
