### ISSUE TITLE
Fix forgotten Craver Questline Changes

### ISSUE THREAD

**Issue by ThanosDeGraf** [wakystuf/ESG-Mod#952]
In 1.3, the Craver Questline was reworked #286 

One of the changes was for the Accelerated Ovipositor: 
+30% manpower capacity on systems and _+150 Defensive manpower deployment limit on systems_.

But later on in 1.5, Defensive Manpower was changed so that there was no Defensive Manpower Limit #506

It goes without saying that this needs fixing xP
My first proposal is that it should instead read: "+# Defensive Manpower per Turn on Systems"

**Comment by NoProblemWithThisAcc** [comment]
Maybe no secondary effect and just +45% manpower capacity on systems instead.

**Comment by wakystuf** [comment]
Nah, I think it's fine as-is. Just build a Sim Camp and use that to feed the war machine.

The +30% is effectively worth far more than it was before with the ground battle changes in 1.4 (@Arpharnator did a great job with those, imho). With far higher levels of system defensive MP, +30% on that larger base is potentially worth thousands and thousands of MP, vs before the impact was much much lower.

**Comment by ThanosDeGraf** [comment]
I'll have to agree, the manpower changes (which are all around an amazing step forward) did make it more potent than before, so that percent planetary MP should stay.

What I am looking for is a stat that would make it worth taking over the other option, you know? Maybe try and diversify the playstyle by rewarding building Planetary MP increasing buildings somehow. As it is, it's just siphoning off Manpower from your invasion fleets with every system you colonise.
