### ISSUE TITLE
Make Craver Terraformation adjust with Gamespeed

### ISSUE THREAD

**Issue by ThanosDeGraf** [wakystuf/ESG-Mod#967]
I've basically implemented the change in #966 .

The module now divides the science output by the game speed multi.
The values for each game speed should be:
- Fast: 1Sc per Dp
- Normal: 0.5Sc per Dp
- Slow: 0.33Sc per Dp
- Endless 0.25 per Dp

I've already tested for endless speeds, and there is just the minor issue that it does not display the adjusted Science Per Depletion point on the Science Tab. (both images taken from the same save, on endless speed.)
![image](https://user-images.githubusercontent.com/46725294/146409290-7813fc3d-2987-42c1-aa92-e191649b1e41.png)
![image](https://user-images.githubusercontent.com/46725294/146409228-0bed8f04-13a0-4e4c-ab30-3c7aee643367.png)

**Comment by wakystuf** [comment]
Should this be tagged as Documented?

**Comment by captaincobbs** [comment]
oops, I had clicked the buttons but I guess it didn't save
