### ISSUE TITLE
Rework/Buff Deed Modules

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#968]
Annihilator Beam and Impregnable Shielding

**Comment by wakystuf** [comment]
![image](https://user-images.githubusercontent.com/79942510/146484110-76b9513d-4c9b-4df4-bc9b-40d6b0e42897.png)

**Comment by wakystuf** [comment]
![image](https://user-images.githubusercontent.com/79942510/146484581-b92f4646-d98a-4173-b2d7-372489984a11.png)

**Comment by NoProblemWithThisAcc** [comment]
Impressive

**Comment by captaincobbs** [comment]
Darn no chance to negate projectiles? Why even bother 😔
