### ISSUE TITLE
Rework Sim Camps

### ISSUE THREAD

**Issue by wakystuf** [wakystuf/ESG-Mod#969]
Split in half, with 2nd building higher on tech tree and costing adamantian

**Comment by ThanosDeGraf** [comment]
Like a cheaper 0.5 indy version, and then another 0.5 indy with steeper cost? Sounds interesting.

**Comment by wakystuf** [comment]
![image](https://user-images.githubusercontent.com/79942510/146484496-555d1176-2963-4316-9f43-c848888af45e.png)
