### ISSUE TITLE
Improved Planet FIDSI Breakdown

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#992]
Show a breakdown of what improvements are affecting the planet's base stats.

Problem: Things like depletion or the craver per pop FIDSI % modifiers will not display properly.
Explanation: Check how enhanced space 2 does it, look at their SimulationDescriptors[StarSystemImprovements].xml

**Comment by wakystuf** [comment]
Similar to the empire improvements, this seems like a good idea if you're willing/have time to do it. I'll change to planned and assign you, but feel free to close it if you don't want to deal with it. This one will be quite tedious to do, I'm pretty sure.

**Comment by captaincobbs** [comment]
Waky you cannot escape

**Comment by wakystuf** [comment]
I think this is mostly impossible due to things like Craver depletion. At a minimum, it will be extremely tedious
