### ISSUE TITLE
New Curio Rewards

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#995]
(All images used are the correct size for the mod)
![StarSystemImprovementWonderPopulation02Large](https://user-images.githubusercontent.com/16710532/147512743-aff7ad16-9204-4d01-a605-aa0c634b1708.png)
Immunity to Blockade Effects (Manpower, FIDSI, and Strategics) (Unique Constructible, Expensive)

![StarSystemImprovementDefense4Large](https://user-images.githubusercontent.com/16710532/147512752-8186bbfc-a54a-42cc-b013-16b91153de28.png)
-20% Enemy Invasion Manpower Limit (Unique Constructible)

**Comment by ThanosDeGraf** [comment]
Bottom one is nuts and I love the idea.

I already have some name ideas: 
- "AI Combat Analytics"
- "Intelligent Battlefield"
- "Smart Trenches"

**Comment by captaincobbs** [comment]
![Militarist](https://user-images.githubusercontent.com/16710532/147527285-e730ea53-81b2-4163-953e-c6bfb8c936dd.png)
+1000 Defensive Bombardment Damage, +15% Troop Health, +100 Enrollment Rate (Expensive)
![ReligiousBuilding](https://user-images.githubusercontent.com/16710532/147527299-9fb6bb22-1c46-47be-be93-e0332f966941.png)
+25% Hero Recovery Rate on Empire, -50% System Upkeep on System (Unique)
![Industrialist](https://user-images.githubusercontent.com/16710532/147527703-aef79a67-8c6b-42bd-b057-a3633a374d4d.png)
+15% Health on Ships made on this System (Unique, Incompatible with other buildings of the same type)
![Scientist](https://user-images.githubusercontent.com/16710532/147527700-2f835d79-c16a-456d-a06c-a5eb459536ae.png)
+1 Movement Point on Ships made on this System (Unique, Incompatible with other buildings of the same type)
![Pacifist](https://user-images.githubusercontent.com/16710532/147527690-fdad21cb-269c-47c7-9e2e-f2e3972b095d.png)
-15% Law Upkeep, +10 Approval, +1 Law Slot when Dictatorship/Autocracy (Hissho only) (Unique, Expensive)
![ProbeBuilding](https://user-images.githubusercontent.com/16710532/147527682-dc49cc37-7cf1-4058-8276-b2e98ad87444.png)
+25% Vision Range on Ships made on this System (Unique, Incompatible with other buildings of the same type)

**Comment by captaincobbs** [comment]
Bang Result Bank = Weaker Blast Effect Battery that costs Hyperium and Titanium
HP Regeneration Module
Upgraded Titanium Shrapnel
Upgraded Antipersonnel Defense Drones
Orichalcix Core Cracker
Orichalcix Colonizer
T2 Strategic Probes
Strategic Coilguns
Strategic Railguns
Strategic Swarm Missiles

**Comment by Eighth-of-Third** [comment]
> Bang Effect Bank = Weaker Blast Effect Battery that costs Hyperium and Titanium
HP Regeneration Module
Upgraded Titanium Shrapnel
Upgraded Antipersonnel Defense Drones
Orichalcix Core Cracker
Orichalcix Colonizer
T2 Strategic Probes

I like all of these.

>Strategic Coilguns
Strategic Railguns
Strategic Swarm Missiles

If we're adding strategic versions of weapons that don't already have them, they also need researchable versions. All the strategic weaponry has a version that's on the tech tree, and the curio version which is weaker but costs less strategics.

**Comment by captaincobbs** [comment]
Doable! We'll need to talk about how we want to handle unlocking these though. Move the white unlocks to the stage unlock, then fill their place on the technologies with a strategic version?

**Comment by Arpharnator** [comment]
that's probably how you want to do it

**Comment by wakystuf** [comment]
For documentation, I believe the buildings all happened, but the modules are still in progress, correct?

**Comment by Kil10naire** [comment]
When the final names and effects weren't listed so I had to go into game and find them on my own. Regardless, I documented all of the buildings as they exist in game, and I suppose I'll just wait on the Modules.
