### ISSUE TITLE
AI Fixes

### ISSUE THREAD

**Issue by captaincobbs** [wakystuf/ESG-Mod#996]
Remove AI Influence per Pop
Lower AI Strategic Resource Boost
~~Forbid UC AI from uncloaking ships~~ not possible
Give Cap to/Forbid AI from building Military Behemoths
Forbid AI from using railguns (it really likes them)

**Comment by Arpharnator** [comment]
Behemoth bonus has been removed.

**Comment by wakystuf** [comment]
Removing one of the items from the list so that I can track it separately

**Comment by wakystuf** [comment]
@FluffiestPrincess 
* The first 2, regarding influence and strats are a reference to the bonuses that the AI gets on higher difficulties (IE, reducing them)
* The third is a prereq that should be built into the decloak EntityAction
* The fourth is regarding their build priorities
* The final one is in the part of ModuleDefinitions[AI_Weapon_Loadout] and ModuleDefinitions[Weapon] that controls the AI's algorithm

**Comment by captaincobbs** [comment]
4th one just do a prerequisite for preventing AI factions from using the military behemoth hull or ship design.
5th one just lower the AI Situation things, make it less desirable.

**Comment by captaincobbs** [comment]
No longer needed due to PatchPreview
